name: baumirein-Core
version: 1.7.2-Alpha
api-version: 1.18
author: baumirein
main: de.baumirein.Main

commands:
  force:
  back:
  invsee:
  trade:
  tpd:
  tpr:
  tpa:
  home:
  sethome:
  sun:
  go:
  set:
  ping:
  warps:
  heal:
  fly:
  troll:
  vanish:
    aliases: [v,spectator]
  gamemode:
    aliases: [gm,gmode]
  craft:
    aliases: [wb,workbench]
  enderchest:
    aliases: [ec,ender]
  repair:
    aliases: [fix,fixall]